### ISSUE TITLE
java.lang.NoSuchMethodError: kotlin.collections.ArraysKt.copyInto

### ISSUE THREAD

**Issue by karthiks3000** [harness/ff-java-server-sdk#131]
I'm trying to use the harness java sdk in a springboot project, but I get the below error on the CfClient intialization.

`java.lang.NoSuchMethodError: kotlin.collections.ArraysKt.copyInto([B[BIII)[B
	at okio.Segment.writeTo(Segment.kt:169) ~[okio-2.8.0.jar:na]
	at okio.Segment.compact(Segment.kt:152) ~[okio-2.8.0.jar:na]
	at okio.Buffer.write(Buffer.kt:1842) ~[okio-2.8.0.jar:na]
	at okio.Buffer.read(Buffer.kt:1854) ~[okio-2.8.0.jar:na]
	at okio.Buffer.writeAll(Buffer.kt:1642) ~[okio-2.8.0.jar:na]
	at okio.Options$Companion.buildTrieRecursive(Options.kt:187) ~[okio-2.8.0.jar:na]
	at okio.Options$Companion.buildTrieRecursive(Options.kt:174) ~[okio-2.8.0.jar:na]
	at okio.Options$Companion.buildTrieRecursive$default(Options.kt:113) ~[okio-2.8.0.jar:na]
	at okio.Options$Companion.of(Options.kt:72) ~[okio-2.8.0.jar:na]
	at okhttp3.internal.Util.<clinit>(Util.kt:70) ~[okhttp-4.9.3.jar:na]
	at okhttp3.internal.concurrent.TaskRunner.<clinit>(TaskRunner.kt:309) ~[okhttp-4.9.3.jar:na]
	at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:41) ~[okhttp-4.9.3.jar:na]
	at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:47) ~[okhttp-4.9.3.jar:na]
	at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.kt:471) ~[okhttp-4.9.3.jar:na]
	at io.harness.cf.ApiClient.initHttpClient(ApiClient.java:119) ~[ff-java-server-sdk-1.1.8.jar:na]
	at io.harness.cf.ApiClient.initHttpClient(ApiClient.java:115) ~[ff-java-server-sdk-1.1.8.jar:na]
	at io.harness.cf.ApiClient.<init>(ApiClient.java:90) ~[ff-java-server-sdk-1.1.8.jar:na]
	at io.harness.cf.client.connector.HarnessConnector.makeApiClient(HarnessConnector.java:57) ~[ff-java-server-sdk-1.1.8.jar:na]
	at io.harness.cf.client.connector.HarnessConnector.<init>(HarnessConnector.java:51) ~[ff-java-server-sdk-1.1.8.jar:na]
	at com.xxx.cpd.service.impl.SdmServiceImpl.getSdmInfo(SdmServiceImpl.java:89) ~[classes/:na]`

My code looks like this - 
```
// Connector Config
        HarnessConfig connectorConfig = HarnessConfig.builder()
                .configUrl("https://config.ff.harness.io/api/1.0")
                .eventUrl("https://config.ff.harness.io/api/1.0")
                .build();

// Create Options
        BaseConfig options = BaseConfig.builder()
                .pollIntervalInSeconds(60)
                .streamEnabled(true)
                .analyticsEnabled(true)
                .build();

// Create the client
        this.cfClient = new CfClient(new HarnessConnector(harnessAPIKey, connectorConfig), options);
        this.cfClient = new CfClient(harnessAPIKey);
        try {
            cfClient.waitForInitialization();
            target = Target.builder()
                    .identifier("javasdk")
                    .name("JavaSDK")
                    .attribute("location", "emea")
                    .build();
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            // Close the SDK
            CfClient.getInstance().close();
        }
```
And the error is thrown on this line -
`this.cfClient = new CfClient(new HarnessConnector(harnessAPIKey, connectorConfig), options);`

Here is my pom.xml - 
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.1.5.RELEASE</version>
        <relativePath /> <!-- lookup parent from repository -->
    </parent>
    <groupId>xxx</groupId>
    <artifactId>cpd-service</artifactId>
    <version>1.0</version>
    <name>CPD API</name>
    <description>Cross Product Dashboard REST API</description>

    <properties>
        <java.version>1.8</java.version>
        <tomcat.version>9.0.21</tomcat.version>
        <jackson.version>2.9.9</jackson.version>
        <jaxb-core.version>2.3.0</jaxb-core.version>
        <jwt-cli.version>1.0</jwt-cli.version>
        <jaxb-impl.version>2.3.0</jaxb-impl.version>
        <io-jsonwebtoken.version>0.6.0</io-jsonwebtoken.version>
        <jaxb-core.version>2.3.0</jaxb-core.version>
        <io-github-benas.version>1.2.0</io-github-benas.version>
        <io-swagger.version>1.5.21</io-swagger.version>
        <io-springfox.version>2.9.2</io-springfox.version>
        <commons-io.version>2.6</commons-io.version>
        <commons-math.version>3.6.1</commons-math.version>
        <jacoco-maven-plugin.version>0.8.3</jacoco-maven-plugin.version>
        <snyk-maven-plugin.version>1.1.1</snyk-maven-plugin.version>
        <maven-jar-plugin.version>3.1.1</maven-jar-plugin.version>
        <skipTests>false</skipTests>
        <skipUTs>${skipTests}</skipUTs>
        <skipITs>true</skipITs>
        <git-commit-id-plugin.version>3.0.0</git-commit-id-plugin.version>
    </properties>
    <repositories>
        <repository>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <id>central</id>
            <name>libs-releases</name>
            <url>https://xxx.jfrog.io/xxx/libs-releases</url>
        </repository>
        <repository>
            <snapshots />
            <id>snapshots</id>
            <name>libs-snapshots</name>
            <url>https://xxx.jfrog.io/xxx/libs-snapshots</url>
        </repository>
        <repository>
            <id>maven2</id>
            <name>maven2</name>
            <url>https://repo1.maven.org/maven2</url>
        </repository>
    </repositories>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-cache</artifactId>
        </dependency>
        <dependency>
            <groupId>net.sf.ehcache</groupId>
            <artifactId>ehcache</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-core</artifactId>
            <version>${jaxb-core.version}</version>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-impl</artifactId>
            <version>${jaxb-impl.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-oauth2-client</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.security.oauth.boot</groupId>
            <artifactId>spring-security-oauth2-autoconfigure</artifactId>
            <version>2.1.2.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-commons</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
            <version>2.1.5.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>io.github.benas</groupId>
            <artifactId>jpopulator</artifactId>
            <version>${io-github-benas.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt</artifactId>
            <version>${io-jsonwebtoken.version}</version>
        </dependency>
        <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-core</artifactId>
            <version>${io-swagger.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-annotations</artifactId>
            <version>${io-swagger.version}</version>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>${io-springfox.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
            <version>${io-springfox.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>${commons-io.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
          <groupId>org.apache.commons</groupId>
          <artifactId>commons-lang3</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-math3</artifactId>
            <version>${commons-math.version}</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/io.rest-assured/rest-assured -->
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- https://mvnrepository.com/artifact/io.rest-assured/json-path -->
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>json-path</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- https://mvnrepository.com/artifact/io.rest-assured/json-schema-validator -->
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>json-schema-validator</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>

        <dependency>
            <groupId>io.harness</groupId>
            <artifactId>ff-java-server-sdk</artifactId>
            <version>1.1.9</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <useSystemClassLoader>false</useSystemClassLoader>
                    <skipTests>${skipUTs}</skipTests>
                    <excludes>
                        <exclude>**/*IT</exclude>
                    </excludes>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>${jacoco-maven-plugin.version}</version>
                <executions>
                    <execution>
                        <id>default-prepare-agent</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>default-report</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>default-check</id>
                        <goals>
                            <goal>check</goal>
                        </goals>
                        <configuration>
                            <rules>
                                <rule>
                                    <element>BUNDLE</element>
                                    <limits>
                                        <limit>
                                            <counter>COMPLEXITY</counter>
                                            <value>COVEREDRATIO</value>
                                            <minimum>0</minimum>
                                        </limit>
                                    </limits>
                                </rule>
                            </rules>
                        </configuration>
                    </execution>
                    <execution>
                        <id>default-prepare-agent-integration</id>
                        <goals>
                            <goal>prepare-agent-integration</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>default-report-integration</id>
                        <goals>
                            <goal>report-integration</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>io.snyk</groupId>
                <artifactId>snyk-maven-plugin</artifactId>
                <version>${snyk-maven-plugin.version}</version>
                <configuration>
                    <failOnSeverity>medium</failOnSeverity>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>add-test-source</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>add-test-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>src/integration-test/java</source>
                            </sources>
                        </configuration>
                    </execution>
                    <execution>
                        <id>add-integration-test-resources</id>
                        <phase>generate-test-resources</phase>
                        <goals>
                            <goal>add-test-resource</goal>
                        </goals>
                        <configuration>
                            <resources>
                                <resource>
                                    <filtering>true</filtering>
                                    <directory>src/integration-test/resources</directory>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <configuration>
                    <skipTests>${skipTests}</skipTests>
                    <skipITs>${skipITs}</skipITs>
                    <includes>
                        <include>**/*IT</include>
                    </includes>
                    <excludes>
                        <exclude>**/*Test</exclude>
                    </excludes>
                </configuration>
                <executions>
                    <execution>
                        <id>integration-test</id>
                        <goals>
                            <goal>integration-test</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>verify</id>
                        <goals>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>pl.project13.maven</groupId>
                <artifactId>git-commit-id-plugin</artifactId>
                <version>${git-commit-id-plugin.version}</version>
                <executions>
                    <execution>
                        <id>get-the-git-infos</id>
                        <goals>
                            <goal>revision</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>validate-the-git-infos</id>
                        <goals>
                            <goal>validateRevision</goal>
                        </goals>
                        <phase>package</phase>
                    </execution>
                </executions>
                <configuration>
                    <dotGitDirectory>${project.basedir}/.git</dotGitDirectory>
                    <prefix>git</prefix>
                    <gitDescribe>
                        <skip>false</skip>
                        <always>false</always>
                        <dirty>-dirty</dirty>
                    </gitDescribe>
                    <includeOnlyProperties>
                        <includeOnlyProperty>git.branch</includeOnlyProperty>
                        <includeOnlyProperty>git.build.time</includeOnlyProperty>
                        <includeOnlyProperty>git.commit.id</includeOnlyProperty>
                    </includeOnlyProperties>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```

**Comment by andybharness** [comment]
Hi @karthiks3000
This is caused when there are conflicting versions of `kotlin-stdlib` on the classpath. SpringBoot 2.1.5 brings in an older version of this JAR (1.2.x) which conflicts with the version used by okhttp 4.9.x (1.4.x). Recommend upgrading to Springboot 2.7.x if you are able to.

If not, as a workaround, you could try adding kotlin-stdlib directly in your dependencies sections to force a later version. For example:

```
    <dependency>
        <groupId>org.jetbrains.kotlin</groupId>
        <artifactId>kotlin-stdlib</artifactId>
        <version>1.4.10</version>
    </dependency>
```
